# Generated by Django 5.2.5 on 2025-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_meal_recipe_alter_pantryimageupload_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, default='pcs', max_length=32),
        ),
    ]
