# Generated by Django 5.2.5 on 2025-09-13 16:03

from django.db import migrations


def fill_units(apps, schema_editor):
    Ingredient = apps.get_model("core", "Ingredient")
    # Fill NULL or empty with 'pcs'
    Ingredient.objects.filter(unit__isnull=True).update(unit="pcs")
    Ingredient.objects.filter(unit="").update(unit="pcs")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_ingredient_unit"),
    ]

    operations = [
        migrations.RunPython(fill_units, migrations.RunPython.noop),
    ]
