# Generated by Django 5.2.5 on 2025-09-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_fill_unit_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrecipe",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
