# Generated by Django 5.2.5 on 2025-09-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_savedrecipe_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pantryimageupload",
            name="image",
            field=models.ImageField(upload_to="media/pantry_uploads/"),
        ),
    ]
