# Generated by Django 5.2.5 on 2025-09-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pantryimageupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiontarget',
            name='diet_type',
            field=models.CharField(blank=True, choices=[('high_protein', 'High Protein'), ('balanced', 'Balanced'), ('keto', 'Keto'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='nutritiontarget',
            name='fiber_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritiontarget',
            name='sugar_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritiontarget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nutritiontarget',
            name='calories',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='nutritiontarget',
            name='carbs_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritiontarget',
            name='fat_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritiontarget',
            name='protein_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
